### PR TITLE
add help command (help.js)

### PR DESCRIPTION
**Pull request by Tushka1**
it lists the commands rn

### CODE REVIEW

**Comment by omrih4** [comment]
hello

**Comment by Tushka1** [comment]
> hello

hi

**Comment by hablethedev** [comment]
Gonna merge this then make some changes to it pretty good PR tho

**Comment by Tushka1** [comment]
> Gonna merge this then make some changes to it pretty good PR tho

:D

**Comment by omrih4** [comment]
iirc you can make changes / request changes directly

**Comment by omrih4** [comment]
to the pr

**Pull request merged**
